app/jobHistory/urls.py
from django.urls import path
from .views import IndexView, JobTimePeriodDetailView

app_name = 'jobHistory'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', JobTimePeriodDetailView.as_view(), name='job-time-period-detail'),
]

app/jobHistorySite/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('administrate/', admin.site.urls),
    path('registration/', include('django.contrib.auth.urls')),
    path('jobHistory/', include('jobHistory.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('jobHistory:index'), permanent=False))
]

app/jobHistory/models.py
import datetime

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class Employer(models.Model):
    class Meta:
        verbose_name = _('Employer')
        constraints  = [
                        models.UniqueConstraint(fields=['short_name', ], name='employer_must_be_unique'),
                       ]

    short_name                          = models.CharField(max_length=50, unique=True, blank=False, null=False, verbose_name=_('Short Name'))
    long_name                           = models.CharField(max_length=254, unique=True, blank=False, null=True, verbose_name=_('Long Name'))
    industry                            = models.CharField(max_length=254, blank=True, null=False, verbose_name=_('Industry'))
    phone                               = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Phone'))
    email                               = models.EmailField(blank=True, null=False, verbose_name=_('Email'))
    addr1                               = models.CharField(max_length=200, blank=True, null=False, verbose_name=_("Address Line 1"))
    addr2                               = models.CharField(max_length=200, blank=True, null=False, verbose_name=_("Address Line 2"))
    addr3                               = models.CharField(max_length=200, blank=True, null=False, verbose_name=_("Address Line 3"))
    city                                = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('City'))
    county_or_parish                    = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('County or Parish'))
    state_or_province                   = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('State or Province'))
    zip_or_postal_code                  = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Zip Code or Postal Code'))
    country                             = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Country'))

    def __str__(self):
        return self.short_name


class Position(models.Model):
    class Meta:
        verbose_name = _('Position')
        constraints  = [
                        models.UniqueConstraint(fields=['employer', 'title', ], name='position_must_be_unique'),
                       ]

    employer                            = models.ForeignKey(Employer, on_delete=models.CASCADE, verbose_name=_('Employer'))
    title                               = models.CharField(max_length=200, blank=False, null=False, verbose_name=_('Title'))
    responsibilities                    = models.TextField(blank=True, null=False, verbose_name=_('Responsibilities'))
    contributions_and_accomplishments   = models.TextField(blank=True, null=False, verbose_name=_('Contributions and Accomplishments'))
    supervisor_name_prefix              = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Supervisor Name Prefix'))
    supervisor_given_name               = models.CharField(max_length=200, blank=False, null=False, verbose_name=_('Supervisor Given Name'))
    supervisor_middle_name              = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Supervisor Middle Name'))
    supervisor_surname                  = models.CharField(max_length=200, blank=False, null=False, verbose_name=_('Supervisor Surname'))
    supervisor_name_suffix              = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Supervisor Name Suffix'))
    supervisor_phone                    = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Supervisor Phone'))
    supervisor_email                    = models.EmailField(blank=True, null=False, verbose_name=_('Supervisor Email'))
    supervisor_addr1                    = models.CharField(max_length=200, blank=True, null=False, verbose_name=_("Supervisor Address Line 1"))
    supervisor_addr2                    = models.CharField(max_length=200, blank=True, null=False, verbose_name=_("Supervisor Address Line 2"))
    supervisor_addr3                    = models.CharField(max_length=200, blank=True, null=False, verbose_name=_("Supervisor Address Line 3"))
    supervisor_city                     = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Supervisor City'))
    supervisor_county_or_parish         = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Supervisor County or Parish'))
    supervisor_state_or_province        = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Supervisor State or Province'))
    supervisor_zip_or_postal_code       = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Supervisor Zip Code or Postal Code'))
    supervisor_country                  = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Supervisor Country'))
    can_contact                         = models.BooleanField(blank=False, null=False, verbose_name=_('Can Contact?'))

    def __str__(self):
        return self.title + " @ " + str(self.employer)


class JobTimePeriod(models.Model):
    class Meta:
        verbose_name = _('Job Time Period')
        constraints  = [
                        models.CheckConstraint(check=(models.Q(is_current_position__exact=True) | models.Q(end_year__isnull=False)), name='require_end_date_if_not_current_position'),
                        models.CheckConstraint(check=(models.Q(is_current_position__exact=False) | (models.Q(end_year__isnull=True) & models.Q(end_month__isnull=True) & models.Q(end_day__isnull=True))), name='leave_end_date_blank_if_current_position'),
                        models.CheckConstraint(check=(models.Q(start_month__isnull=False) | models.Q(start_day__isnull=True)), name='require_start_month_if_start_day_specified'),
                        models.CheckConstraint(check=(models.Q(end_year__isnull=False) | (models.Q(end_month__isnull=True) & models.Q(end_day__isnull=True))), name='require_end_year_if_end_month_specified'),
                        models.CheckConstraint(check=(models.Q(end_month__isnull=False) | models.Q(end_day__isnull=True)), name='require_end_month_if_end_day_specified'),
                        models.UniqueConstraint(fields=['position', 'start_year', 'start_month', 'start_day', 'is_current_position'], name='job_time_period_must_be_unique_A'),
                        models.UniqueConstraint(fields=['position', 'start_year', 'start_month', 'start_day', 'end_year', 'end_month', 'end_day'], condition=models.Q(is_current_position__exact=False), name='job_time_period_start_and_end_date_must_be_unique_if_not_current_position'),
                       ]

    position                            = models.ForeignKey(Position, on_delete=models.CASCADE, verbose_name=_('Position'))
    start_year                          = models.PositiveIntegerField(blank=False, null=False, verbose_name=_('Start Year'))
    start_month                         = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(12)], verbose_name=_('Start Month'))
    start_day                           = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(31)], verbose_name=_('Start Day'))
    is_current_position                 = models.BooleanField(blank=False, null=False, default=True, verbose_name=_('Current Position?'))
    end_year                            = models.PositiveIntegerField(blank=True, null=True, verbose_name=_('End Year'))
    end_month                           = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(12)], verbose_name=_('End Month'))
    end_day                             = models.PositiveSmallIntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(31)], verbose_name=_('End Day'))
    starting_pay                        = models.CharField(max_length=50, blank=False, null=False, verbose_name=_('Starting Pay'))
    ending_pay                          = models.CharField(max_length=50, blank=False, null=False, verbose_name=_('Ending Pay'))
    hours_per_week                      = models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=_('Hours per Week'))
    contributions_and_accomplishments   = models.TextField(blank=True, null=False, verbose_name=_('Contributions and Accomplishments'))
    work_city                           = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Work City'))
    work_county_or_parish               = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Work County or Parish'))
    work_state_or_province              = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Work State or Province'))
    work_zip_or_postal_code             = models.CharField(max_length=50, blank=True, null=False, verbose_name=_('Work Zip Code or Postal Code'))
    work_country                        = models.CharField(max_length=200, blank=True, null=False, verbose_name=_('Work Country'))

    @property
    def startDate(self):
        return datetime.date(self.start_year, self.start_month or 1, self.start_day or 1)

    @property
    def endDate(self):
        if self.is_current_position:
            return datetime.date.today()
        else:
            return datetime.date(self.end_year or datetime.MINYEAR, self.end_month or 1, self.end_day or 1)

    def __str__(self):
        ret_val = str(self.position)
        ret_val += " from "
        try:
            ret_val += str(self.startDate)
        except ValueError as e:
            ret_val += '<Invalid start date value>'
        ret_val += " to "
        if self.is_current_position:

app/jobHistory/views.py
import operator

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView #, SingleObjectTemplateResponseMixin

from .models import JobTimePeriod


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'jobHistory/index.html'
    context_object_name = 'chronological_job_list'

    def get_queryset(self):
        job_time_periods = JobTimePeriod.objects.all()
        return sorted(job_time_periods, key=operator.attrgetter('endDate'), reverse=True)


class JobTimePeriodDetailView(LoginRequiredMixin, DetailView):
    model = JobTimePeriod

app/templates/jobHistory/index.html
{% extends "base/base.html" %}

{% block title %}Your Job History{% endblock %}

{% block content %}
    <h1>Your Job History</h1>
    <table>
        <thead>
            <tr><th>Title</th><th>Employer</th><th>From</th><th>To</th><th>Details</th></tr>
        </thead>
        <tbody>
            {% for job_time_period in chronological_job_list %}
                <tr>
                    <td>{{ job_time_period.position.title }}</td>
                    <td>{{ job_time_period.position.employer.long_name }}</td>
                    <td>{{ job_time_period.startDate }}</td>
                    <td>{{ job_time_period.endDate }}</td>
                    <td><a href="{% url 'jobHistory:job-time-period-detail' job_time_period.pk %}">More...</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/jobHistory/jobtimeperiod_detail.html
{% extends "base/base.html" %}

{% block title %}Detail - {{ object }}{% endblock %}

{% block content %}
    <div id="job-time-period-detail">
        <h1>{{ object }}</h1>
        <p><span class="detail-label"><strong>Title: </strong></span><span class="detail-data">{{ object.position.title }}</span></p>
        <p><span class="detail-label"><strong>Employer: </strong></span><span class="detail-data">{{ object.position.employer.long_name }}</span></p>
        <p><span class="detail-label"><strong>Current Position? </strong></span><span class="detail-data">{{ object.current_position|yesno }}</span></p>
        <p><span class="detail-label"><strong>Start Year: </strong></span><span class="detail-data">{{ object.start_year }}</span></p>
        <p><span class="detail-label"><strong>Start Month: </strong></span><span class="detail-data">{{ object.start_month }}</span></p>
        <p><span class="detail-label"><strong>Start Day: </strong></span><span class="detail-data">{{ object.start_day }}</span></p>
        <p><span class="detail-label"><strong>End Year: </strong></span><span class="detail-data">{{ object.end_year }}</span></p>
        <p><span class="detail-label"><strong>End Month: </strong></span><span class="detail-data">{{ object.end_month }}</span></p>
        <p><span class="detail-label"><strong>End Day: </strong></span><span class="detail-data">{{ object.end_day }}</span></p>
        <p><span class="detail-label"><strong>Position Responsibilities: </strong></span><span class="detail-data"><br />
                {{ object.position.responsibilities|linebreaksbr }}</span></p>
        <p><span class="detail-label"><strong>Contributions and Accomplishments in Position: </strong></span><span class="detail-data"><br />
                {{ object.position.contributions_and_accomplishments|linebreaksbr }}</span></p>
        <p><span class="detail-label"><strong>Contributions and Accomplishments During This Specific Time Period: </strong></span><span class="detail-data"><br />
                {{ object.contributions_and_accomplishments|linebreaksbr }}</span></p>
        <p><span class="detail-label"><strong>City Worked In: </strong></span><span class="detail-data">{{ object.work_city }}</span></p>
        <p><span class="detail-label"><strong>County/Parish: </strong></span><span class="detail-data">{{ object.work_county_or_parish }}</span></p>
        <p><span class="detail-label"><strong>State/Province: </strong></span><span class="detail-data">{{ object.work_state_or_province }}</span></p>
        <p><span class="detail-label"><strong>Zip/Postal Code: </strong></span><span class="detail-data">{{ object.work_zip_or_postal_code }}</span></p>
        <p><span class="detail-label"><strong>Country: </strong></span><span class="detail-data">{{ object.work_country }}</span></p>
        <p><span class="detail-label"><strong>Hours Per Week: </strong></span><span class="detail-data">{{ object.hours_per_week }}</span></p>
        <p><span class="detail-label"><strong>Starting Pay: </strong></span><span class="detail-data">{{ object.starting_pay }}</span></p>
        <p><span class="detail-label"><strong>Ending Pay: </strong></span><span class="detail-data">{{ object.ending_pay }}</span></p>
        <p>&nbsp;</p>
        <div id="supervisor-detail">
            <h2>Supervisor</h2>
            <div id="supervisor-name">
                <h3>Supervisor Name</h3>
                <p><span class="detail-label"><strong>Prefix: </strong></span><span class="detail-data">{{ object.position.supervisor_name_prefix }}</span></p>
                <p><span class="detail-label"><strong>First/Given Name: </strong></span><span class="detail-data">{{ object.position.supervisor_given_name }}</span></p>
                <p><span class="detail-label"><strong>Middle: </strong></span><span class="detail-data">{{ object.position.supervisor_middle_name }}</span></p>
                <p><span class="detail-label"><strong>Last Name/Surname: </strong></span><span class="detail-data">{{ object.position.supervisor_surname }}</span></p>
                <p><span class="detail-label"><strong>Suffix: </strong></span><span class="detail-data">{{ object.position.supervisor_name_suffix }}</span></p>
            </div>
            <p>&nbsp;</p>
            <p><span class="detail-label"><strong>Phone: </strong></span><span class="detail-data">{{ object.position.supervisor_phone }}</span></p>
            <p><span class="detail-label"><strong>Email: </strong></span><span class="detail-data">{{ object.position.supervisor_email }}</span></p>
            <div id="supervisor-address">
                <h3>Supervisor Address</h3>
                <p><span class="detail-label"><strong>Address Line 1: </strong></span><span class="detail-data">{{ object.position.supervisor_addr1 }}</span></p>
                <p><span class="detail-label"><strong>Address Line 2: </strong></span><span class="detail-data">{{ object.position.supervisor_addr2 }}</span></p>
                <p><span class="detail-label"><strong>Address Line 3: </strong></span><span class="detail-data">{{ object.position.supervisor_addr3 }}</span></p>
                <p><span class="detail-label"><strong>City: </strong></span><span class="detail-data">{{ object.position.supervisor_city }}</span></p>
                <p><span class="detail-label"><strong>County/Parish: </strong></span><span class="detail-data">{{ object.position.supervisor_county_or_parish }}</span></p>
                <p><span class="detail-label"><strong>State/Province: </strong></span><span class="detail-data">{{ object.position.supervisor_state_or_province }}</span></p>
                <p><span class="detail-label"><strong>Zip/Postal Code: </strong></span><span class="detail-data">{{ object.position.supervisor_zip_or_postal_code }}</span></p>
                <p><span class="detail-label"><strong>Country: </strong></span><span class="detail-data">{{ object.position.supervisor_country }}</span></p>
            </div>
            <p>&nbsp;</p>
            <p><span class="detail-label"><strong>Can Contact? </strong></span><span class="detail-data">{{ object.position.can_contact|yesno }}</span></p>
        </div>
    </div>
{% endblock %}